version: '2'
services:
 web:
   build: .
   depends_on:
    - mysql
   environment: 
    - JOOMLA_DB_HOST=mysql
    - JOOMLA_DB_PORT=3306
    - JOOMLA_DB_USER=root
    - JOOMLA_DB_PASSWORD=vulhub
    - JOOMLA_DB_NAME=joomla
   ports:
    - "8082:80"
   command: apache2-foreground
   networks:
      net1:
        ipv4_address: 192.168.10.9 
 mysql:
   image: mysql:5.7
   environment: 
    - MYSQL_ROOT_PASSWORD=vulhub
   networks:
      net1:
        ipv4_address: 192.168.10.10 

networks:
  net1:
    ipam:
      config:
        - subnet: "192.168.10.0/24"