version: '2'
services:
 web:
   build: .
   depends_on:
    - mysql
   environment: 
    - JOOMLA_DB_HOST=mysql
    - JOOMLA_DB_PORT=3306
    - JOOMLA_DB_USER=root
    - JOOMLA_DB_PASSWORD=vulhub
    - JOOMLA_DB_NAME=joomla
   ports:
    - "8082:80"
   command: apache2-foreground

 mysql:
   image: mysql:5.7
   environment: 
    - MYSQL_ROOT_PASSWORD=vulhub